### PR TITLE
Fix logging bug and clean up on helm chart

### LINKED ISSUE #13: FfDL logging issues with Elastic Search
The FfDL Elastic Search sometimes has an overhead issue when creating the emetrics/logline mapping.
```
[2018-02-15T18:11:21,334][INFO ][o.e.c.m.MetaDataMappingService] [VPF0eed] [dlaas_learner_data/Of58W91xS-6OlsuQEGByzw] update_mapping [logline]
[2018-02-15T18:11:36,852][INFO ][o.e.m.j.JvmGcMonitorService] [VPF0eed] [gc][556] overhead, spent [258ms] collecting in the last [1s]
```

When the Elastic Search works properly, it should have the following logs for mapping update/create.

```
[2018-02-15T17:52:52,598][INFO ][o.e.c.m.MetaDataMappingService] [R7H6R6o] [dlaas_learner_data/d-NMzvwRT_CXgMwHOBinTg] update_mapping [logline]
[2018-02-15T17:54:51,289][INFO ][o.e.c.m.MetaDataMappingService] [R7H6R6o] [dlaas_learner_data/d-NMzvwRT_CXgMwHOBinTg] create_mapping [emetrics]
```

### PR DESCRIPTION
**Pull request by Tomcli**
* Fix #13 Logging bug. (It was caused by insufficient memory and cpu with the log collector)
* Rename old-tf-model to tf-summary-model.
* Clean up on some old internal secret dependencies on helm chart.

DCO 1.1 Signed-off-by: Tommy Li <tommy.chaoping.li@ibm.com>

### CODE REVIEW

File: lcm/service/lcm/constants.go [hunk 1]
```diff
@@ -78,8 +78,8 @@ const (
 	loadModelMemInMB=50
 	loadTrainingDataMilliCPU=20
 	loadTrainingDataMemInMB=300
-	logCollectorMilliCPU=20
-	logCollectorMemInMB=100
+	logCollectorMilliCPU=60
+	logCollectorMemInMB=300
 	controllerMilliCPU=20
```
Comment (animeshsingh) [inline lcm/service/lcm/constants.go]: How did we come up with these numbers?

Comment (Tomcli) [reply lcm/service/lcm/constants.go]: Similar to the Load Training Data memory, giving log collector 3x capacity seems to be the right fix. 2x capacity will work on our example but it will be insufficient again with a bigger job. I am working on moving these constants to the helm chart, so in the future users can just customize these number based on their needs.
